### PR TITLE
Add atMostNTimes option

### PR DESCRIPTION
**Pull request by Jack-Works**
Add an option to clean cache after N calls.

### CODE REVIEW

**Comment by Jack-Works** [comment]
@vilic hello? any suggestions?

**Comment by vilicvane** [comment]
@Jack-Works Hi, thanks for this PR.

Sorry I don't have a contribution guide ready.

The main concerns from me are:

1. The name of the option, do we have better choice?
2. Code style, this project is configured with prettier for code formatting.
3. Extra changes to other things irrelevant: including README and comments in code.

I think we should come out with a better option name though.

**Comment by Jack-Works** [comment]
1. can't find a more clear option name. Any idea?

2. OK I'll format code using prettier next change.

3. Irrelevant stuff:

    Readme: emm what is irrelevant?

    Comments in code: if you mean JSDoc comment on MemorizeOptions interface, that kind of comment will show in user's code editor (at least vscode) when they hover on the attribute or when they filling options to help user figure out what is this option is.

**Comment by vilicvane** [comment]
@Jack-Works Sorry I am really busy these days, and I will get back to this PR once I get some free time.

**Comment by Jack-Works** [comment]
@vilic got formatted with prettier

**Comment by Jack-Works** [comment]
@vilic Hello?

**Comment by Jack-Works** [comment]
@vilic Hello? I'm gonna clean up my forked repo

**Comment by vilicvane** [comment]
@Jack-Works I am so sorry... Just couldn't think about a better name for this. Can you create a new PR to the `at-most-n-times` branch I just created? I will merge it there for now.

**Comment by Jack-Works** [comment]
Thanks, see #3 now

**Pull request closed without merging**
